language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: XjJxECAifGyL5cUKBYvAld+xwOTae2dpXY1z2MoxrqIauQAh5LEIbwKj4AQwmvmknPCti+Dp31xgQ5oOtxU6AdVIdoFjqmCcAX/Ee0Ol58HpdRo4h5K5zzr01TieXKh/k0FJ5FKM3HDxr1B+pOICvjRpsqYC+aoRTlbRCgkDFOA=
  - secure: Q2R/AbL2A1VhjFJQmoLozQDYy4eFOhvZnPGz3thk1qgx8JuHGe53e2kVlvec/MkyLHXGt05sw2RpLPvTCec56Y1Y5661UMRNDGQttc8YOs78zvD4ID5aAHDlqQ5Nk95TN/Pp8bMcflJ/wpZgzvujkSVoLVnBkz9cALlzibk01ds=
